### ISSUE TITLE
[Task] 이슈 템플릿 생성

### ISSUE THREAD

**Issue by ciocio97** [life-secretary/front#1]
### ISSUE
- Group :  `Front`
- Type : `Task`
- Detail : 프론트엔드 이슈 템플릿 생성

### TODO
1. [x] 프론트엔드 `Label` 생성 
2. [x] 프론트엔드 이슈 템플릿 생성
3. [x] 프론트엔드 1차 개발 전체 마일스톤 생성

### LABELS
- Estimated time : `0.25md`
- Sprint : ``
- Urgency : `Low`
