### ISSUE TITLE
[Feature] Read the scrap contents list

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#10]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Develop the function to show saved contents list displayed on the save screen

### TODO
1. [x] Using GET API for fetching saved contents list => 40m
2. [x] Setting up the recoil state => 20m
3. [ ] Rendering user's saved contents list => 30m

### LABELS
- Estimated time : `0.5md`
- Sprint : `3`
- Urgency : `Middle`
