### ISSUE TITLE
[Feature] Error handling

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#101]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Error handling when error occurs

### TODO
1. [x] Adding error handling logic => 7h
2. [x] Adding loading handling logic => 6h
3. [x] Creating ErrorBoundary Component => 3h
 

### LABELS
- Estimated time : `2md`
- Sprint : `6` ~ `8`
- Urgency : `Middle`
