### ISSUE TITLE
[Feature] Edit the scrap contents list

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#11]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Develop the function to edit saved contents list

### TODO
1. [x] Using DELETE API for unscrap contents => 2h
2. [x] Creating a multiple select form => 1h
3. [x] Updating user's scrap contents list data => 2h

### LABELS
- Estimated time : `1md`
- Sprint : `2` ~ `3`
- Urgency : `Middle`
