### ISSUE TITLE
[Bug] 홈 콘텐츠 리스트에서 더보기 버튼 터치 후 이동 시 필터가 제대로 적용되지 않는 버그

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#178]
### ISSUE
- Group :  `Front`
- Type : `Bug`
- Detail : 홈 콘텐츠 리스트 내의 더보기 버튼 터치 후 이동하는 콘텐츠 목록 화면에서 필터가 모두 '조회순'으로 설정됨.

### TODO
1. [x] 유사한 사용자 -> 추천 카테고리 / '조회순' 
2. [x] 인기 많은 콘텐츠 -> 사용자 선택 카테고리 / '저장순'
3. [x] 최근 업데이트 -> 전체 카테고리 / '최신순'

### LABELS
- Estimated time : `md`
- Sprint : ``
- Urgency : `Middle`
