### ISSUE TITLE
[Feature] Create main category list & bind data

### ISSUE THREAD

**Issue by ciocio97** [life-secretary/front#19]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : 대분류 리스트 조회 API 데이터 바인딩 및 테스트

### TODO
1. [x] 컨텐츠 목록 퍼블리싱 (컴포넌트 활용)
2. [x] 할 일 목록 퍼블리싱 (컴포넌트 활용)
3. [ ] 카테고리 목록 선택 박스 퍼블리싱
4. [ ] 컨텐츠 목록 데이터 바인딩 및 테스트
5. [ ] 할 일 목록 데이터 바인딩 및 테스트

### LABELS
- Estimated time : `0.5md`
- Sprint : ``
- Urgency : `Middle`
