### ISSUE TITLE
[Task] React Native 개발 환경 설정

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#23]
### ISSUE
- Group :  `Front`
- Type : `Task`
- Detail : Set up a react native project development environment  

### TODO
1. [x] Creating a React Native project 
2. [x] Building the android app 
3. [x] Building the ios app

### LABELS
- Estimated time : `1md`
- Sprint : ``
- Urgency : `High`
