### ISSUE TITLE
[Feature] Global Styles

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#24]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Apply the global styles to the project app

### TODO
1. [x] Creating a global layout => 1.5h
2. [x] Setting up default font  => 1h
3. [x] Setting up design system  i.e) color palette, font, spacing... => 2h

### LABELS
- Estimated time : `0.5md`
- Sprint : ``
- Urgency : `High`
