### ISSUE TITLE
[Feature] Delete a todo item

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#25]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Develop the function to delete a todo

### TODO
1. [x] Setting up the recoil state => 30m
2. [x] Creating the delete confirm modal => 10m
3. [x] Using DELETE API for deleting a todo => 40m
4. [x] Updating todo list data => 40m

### LABELS
- Estimated time : `0.5md`
- Sprint : `2`
- Urgency : `Middle`
