### ISSUE TITLE
[Feature] Complete a todo item

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#26]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Develop the function to complete a todo

### TODO
1. [ ] Setting up the recoil state
2. [ ] Using PUT API for completing a todo
3. [ ] Updating user's completed list data
4. [ ] Creating the completion bottom sheet => 40m

### LABELS
- Estimated time : `1md`
- Sprint : ``
- Urgency : `Middle`
