### ISSUE TITLE
[Feature] React Navigation 적용

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#28]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Apply react navigation to the app

### TODO
1. [X] Installing react navigation module
2. [X] Setting up app navigation
3. [X] Adding a tab navigation

### LABELS
- Estimated time : `0.5md`
- Sprint : ``
- Urgency : `High`
