### ISSUE TITLE
[Feature] Home Image Carousel

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#3]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Create the contents carousel displayed on the main screen

### TODO
1. [x] Installing a carousel library => 20m
2. [ ] Setting up a carousel component => 1h
3. [ ] Fetching the data => 10m

### LABELS
- Estimated time : `0.75md`
- Sprint : ``
- Urgency : `Middle`
