### ISSUE TITLE
[Feature] Create common Modal component

### ISSUE THREAD

**Issue by ciocio97** [life-secretary/front#31]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Create common `Modal` component & Apply in "Detail" modal

### TODO
1. [x] create `Modal` component in 📁 component/common folder
2. [x] make "Detail" `Modal` in 📁 component/ui folder
3. [ ] create Modal status Recoil store

### LABELS
- Estimated time : `1.5md`
- Sprint : ``
- Urgency : `Low`

**Comment by ciocio97** [comment]
`Modal` 컴포넌트 상태를 공통으로 관리하는 프로세스는 조금 더 고민해보겠습니다. (TODO 3번째 항목)
