### ISSUE TITLE
[Feature] Home Contents Lists

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#4]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Create contents lists displayed on the main screen

### TODO
1. [ ] Rendering the list of popular contents based on my interests
2. [ ] Rendering the list of recent updated contents 
3. [ ] Rendering the list of contents that users similar to me are reading a lot

### LABELS
- Estimated time : `1md`
- Sprint : ``
- Urgency : `Middle`
