### ISSUE TITLE
[Feature] Create transparent background modal in common

### ISSUE THREAD

**Issue by ciocio97** [life-secretary/front#47]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Create transparent background modal in common

### TODO
1. [x] One button modal (column)
![스크린샷 2024-03-12 오후 3 35 38](https://github.com/life-secretary/front/assets/80025242/32d8c480-414b-4cb5-9013-bfdb80fb088c)
2. [x] Two button modal (column)
![스크린샷 2024-03-12 오후 3 39 02](https://github.com/life-secretary/front/assets/80025242/f99413ef-4b52-436b-9672-7414bb8e811b)
3. [x] Two button modal (row)
![스크린샷 2024-03-12 오후 3 39 43](https://github.com/life-secretary/front/assets/80025242/a34e6147-0ca7-4852-b468-3804ccf5e41d)

### LABELS
- Estimated time : `1md`
- Sprint : ``
- Urgency : `Middle`
