### ISSUE TITLE
[Feature] Todo Screen Publishing

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#5]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Work on the todo screen publishing according to the design

### TODO
1. [x] Designing the component structure => 2h
2. [x] Creating the components depend on domain => 4h
3. [x] Creating a blank page => 30m

### LABELS
- Estimated time : `1md`
- Sprint : ``
- Urgency : `Middle`
