### ISSUE TITLE
[Feature] Modify the component styles

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#57]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Modify the component styles in the app

### TODO
1. [x] Modifying HomeScreen styles => 4h
2. [x] Modifying TodoScreen styles => 8h
3. [x] Modifying SaveScreen styles => 3h

### LABELS
- Estimated time : `1md`
- Sprint : `1`
- Urgency : `High`
