### ISSUE TITLE
[Feature] Read a todo list

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#6]
### ISSUE
- Group :  `Front`
- Type : `Feature` 
- Detail : Develop the function to show a to-do list displayed on the to-do screen

### TODO

1. [x] Setting up the recoil state => 2h
2. [x] Using GET API for fetching user's to-do list => 1h 30m
3. [x] Rendering user's to-do list => 1h 30m

### LABELS
- Estimated time : `1.5md`
- Sprint : `2`
- Urgency : `Middle`
