### ISSUE TITLE
[Feature] Delete a sub todo item

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#66]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Develop the function to delete a sub todo item

### TODO
1. [x] Setting up the recoil state => 1h
2. [x] Using DELETE API for deleting a sub todo => 30m
3. [x] Updating sub todo list data => 30m

### LABELS
- Estimated time : `0.5md`
- Sprint : `2`
- Urgency : `Middle`
