### ISSUE TITLE
[Feature] Add a todo item

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#7]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Develop the function to add a todo

### TODO
1. [ ] Creating a form => 3h
2. [ ] Adding the select option => 2h
3. [ ] Setting up the recoil state => 30m
4. [ ] Using POST API for adding a todo
5. [x] Creating an added todo card => 30m 

### LABELS
- Estimated time : `2md`
- Sprint : ``
- Urgency : `Middle`
