### ISSUE TITLE
[Feature] Delete the user

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#85]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Develop the function to delete the user

### TODO
1. [x] Using DELETE API to delete the user => 20m
2. [x] Using POST API to send the withdrawal reasons => 1h
3. [x] Applying select multiple withdrawal reasons => 20m

### LABELS
- Estimated time : `1md`
- Sprint : `6`~`7`
- Urgency : `Middle`
