### ISSUE TITLE
[Feature] Save Screen Publishing

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#9]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : Work on the save screen web publishing according to design

### TODO
1. [x] Designing the component structure => 30m
2. [x] Creating the components depend on domain => 3h
3. [x] Creating a blank page => 30m

### LABELS
- Estimated time : `1md`
- Sprint : ``
- Urgency : `Middle`
