### ISSUE TITLE
[Feature] Read the home contents list

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#91]
### ISSUE
- Group :  `Front`
- Type : `Feature` 
- Detail : Develop the function to read the home contents list

### TODO
1. [ ] Using GET API to filter home contents list => 1h 30m
2. [ ] Rendering the contents list similar users are reading
4. [x] Rendering the last updated contents list => 30m
5. [ ] Rendering the popular contents list => 1h

### LABELS
- Estimated time : `1md`
- Sprint : `2`~`3`
- Urgency : `Middle`
